# Generated by Django 2.2.4 on 2023-07-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_App', '0002_auto_20230723_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.AddField(
            model_name='order',
            name='cars',
            field=models.ManyToManyField(related_name='order_car', to='Solo_App.Car'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cars',
            field=models.ManyToManyField(related_name='cart_cars', to='Solo_App.Car'),
        ),
    ]
